### ISSUE TITLE
Backend silently fails to push messages in the queue

### ISSUE THREAD

**Issue by Schwenger** [Schwenger/House-Of-Tweets#3]
_Sometimes_ the backend stops pushing messages in the respective queue.
Tweets do get received and appropriate information is printed on stdin, but the data never reaches the queue. 
However, rabbitmq reports that there is still a connection to the BE; it is listed as consumer for citizenuser, citizenbird, and persists. There is no information available regarding the connection to the tweets queue since its not a subscription.

As soon as this state is reached, there is no recovering.

**Comment by BenWiederhake** [comment]
As large parts are rewritten: Test it now, and if it happens, send me the log.  Closing for readability, feel free to reopen.
