### ISSUE TITLE
Decide on response-trigger

### ISSUE THREAD

**Issue by BenWiederhake** [Schwenger/House-Of-Tweets#7]
Current: on usage of either of these hashtags: `#HouseOfTweets`, `#HoT`

Problem:  Don't respond to #hot, that might be not express-consent-y enough.

Options:
- listen for `@HouseOfTweetsSB:` instead — bad! The user `@HouseOfTweetsS` is unrelated, and the user `@HouseOfTweets` is confusing. Also see #8
- drop support for `#HoT`, then it's pretty obvious what they tried to achieve.

**Comment by Schwenger** [comment]
- Drop NAck support for #HoT. In case of a #HoT w/o any bird in the message, there is a good change they did not mean to contact us, thus we omit the NAck. If they use #HoT to label a bird, however, we will react falsely by ack'ing the change. But I'd estimate the change rather low, that a politician will do something like that.

**Comment by BenWiederhake** [comment]
This is more effort than dropping #HoT entirely.

**Comment by Schwenger** [comment]
Well, but not by much, no?
`send nack unless tweet.content contains #hot`

**Comment by BenWiederhake** [comment]
Funktioniert nicht.  Gegenbeispiel: `Ich will Amsel #HouseOfTweets #hot`

**Comment by BenWiederhake** [comment]
Okay, kann ich machen, aber der Algorithmus sieht halt anders aus.

**Comment by Schwenger** [comment]
In your example they would not get a NAck even if they would have spelled Amsel wrong. But that's not too bad as well. The system is not perfect, but better than dropping #HoT for good.
